name: Auto Crypto Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # restart setiap 6 jam

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350    # 5 jam 50 menit, aman sebelum limit GitHub

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install requests websockets numpy pandas

    - name: Export Secrets
      run: |
        echo "BG_API_KEY=${{ secrets.BG_API_KEY }}" >> $GITHUB_ENV
        echo "BG_API_SECRET=${{ secrets.BG_API_SECRET }}" >> $GITHUB_ENV
        echo "BG_API_PASS=${{ secrets.BG_API_PASS }}" >> $GITHUB_ENV

    - name: Run NORMAL bot
      run: python3 main.py

    - name: Run SNIPER bot
      run: python3 sniper.py
      
